[dev]
  command = "npx eleventy --config=.eleventy/.eleventy.js --serve --quiet"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "/bookmarks/tags/*"
  to = "/bookmarks/tags/index.html"
  status = 200
  force = true
