backend:
  name: git-gateway
  branch: main
  squash_merges: true

local_backend: true

media_folder: "_public/images"

collections:
  - name: "bookmarks"
    label: "Bookmarks"
    folder: "content/bookmarks"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "bookmark" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: 'url', widget: "url" }
      - { label: "Body", name: "body", widget: "text", default: " " }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["bookmark"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
