backend:
  name: git-gateway
  branch: main
  squash_merges: true

local_backend: true

media_folder: "src/_public/images"

collections:
  - name: "blogposts"
    label: "Blog posts"
    label_singular: "Blog post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Publish", name: "permalink", widget: "publish", default: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["blog"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tweet URL", name: "tweetUrl", widget: 'url', default: "", required: false  }
      - { label: "Toot URL", name: "tootUrl", widget: 'url', default: "", required: false  }
      - { label: "Body", name: "body", widget: "markdown", default: " " }

  - name: "bookmarks"
    label: "Bookmarks"
    label_singular: "Bookmark"
    folder: "content/bookmarks"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "bookmark" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: 'url', widget: "url" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["bookmark"] }
      - { label: "Body", name: "body", widget: "text", default: " " }
      - { label: "Publish Date", name: "date", widget: "datetime" }

  - name: "likes"
    label: "Likes"
    label_singular: "Like"
    folder: "content/likes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    summary: "{{url}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "like" }
      - { label: "Tags", name: "tags", widget: "hidden", default: ["like"] }
      - { label: "Title", name: "title", widget: "string", default: "Like of" }
      - { label: "Target URL", name: 'url', widget: "url" }
      - { label: "Silo", name: 'silo', widget: 'select', options: ['twitter', 'mastodon', 'indieweb'], default: ['indieweb'] }
      - { label: "Publish Date", name: "date", widget: "datetime" }

  - name: "notes"
    label: "Notes"
    label_singular: "Note"
    folder: "content/notes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    summary: "{{body}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "note" }
      - { label: "Tags", name: "tags", widget: "hidden", default: ["note"] }
      - { label: "Title", name: "title", widget: "string", default: "Note" }
      - { label: "Tweet URL", name: "tweetUrl", widget: 'url', default: "", required: false  }
      - { label: "Toot URL", name: "tootUrl", widget: 'url', default: "", required: false  }
      - { label: "Body", name: "body", widget: "text", default: " " }
      - { label: "Publish Date", name: "date", widget: "datetime" }

  - name: "replies"
    label: "Replies"
    label_singular: "Reply"
    folder: "content/replies"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    summary: "{{url}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "reply" }
      - { label: "Tags", name: "tags", widget: "hidden", default: ["reply"] }
      - { label: "Title", name: "title", widget: "string", default: "Reply to" }
      - { label: "Target URL", name: 'url', widget: "url" }
      - { label: "Silo", name: 'silo', widget: 'select', options: ['twitter', 'mastodon', 'indieweb'], default: ['indieweb'] }
      - { label: "Tweet URL", name: "tweetUrl", widget: 'url', default: "", required: false  }
      - { label: "Toot URL", name: "tootUrl", widget: 'url', default: "", required: false  }
      - { label: "Body", name: "body", widget: "markdown", default: " " }
      - { label: "Publish Date", name: "date", widget: "datetime" }
