name: Send Webmentions

on: [push]

jobs:
  send-webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Find changed files
        env:
          AFTER: ${{ github.event.after }}
          BEFORE: ${{ github.event.before }}
        # run: git diff --name-only $BEFORE $AFTER >> changed-files.txt
        run: git log
