name: Send Webmentions

on: [push]

jobs:
  send-webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Find last sha
        env:
          AFTER: ${{ github.event.after }}
          BEFORE: ${{ github.event.before }}
        run: |
          echo "$BEFORE"
          echo "$AFTER"
