name: Add syndication link

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Add syndication link]

jobs:
  add-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Put post source file in variable
        run: echo "POST_SOURCE=$(echo '${{ github.event.client_payload.source }}' | sed 's/https:\/\/www\.petergoes\.nl\//content\//' | sed 's/\/$/.md/')" >> $GITHUB_ENV

      - name: Add Syndication urls
        run: |
          sed --in-place='' 's@tweetUrl: \"\"@tweetUrl: ${{ github.event.client_payload.tweetUrl }}@' $POST_SOURCE

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update syndication urls
          branch: update-syndication-url
          delete-branch: true
          assignees: petergoes
          title: Update syndication urls
          body: |
            Update syndication urls
            - Auto-generated by [create-pull-request][1]
            
            Subscribed: @petergoes

            [1]: https://github.com/peter-evans/create-pull-request
