name: Add syndication link

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Add syndication link]

jobs:
  add-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Put post source file in variable
        run: echo "POST_SOURCE=$(echo '${{ github.event.client_payload.source }}' | sed 's/https:\/\/www\.petergoes\.nl\//content\//' | sed 's/\/$/.md/')" >> $GITHUB_ENV

      - name: Add Syndication urls
        run: |
          sed --in-place='' 's|tweetUrl:.*$|tweetUrl: "${{ github.event.client_payload.tweetUrl }}"|' $POST_SOURCE
          sed --in-place='' 's|tootUrl:.*$|tootUrl: "${{ github.event.client_payload.tootUrl }}"|' $POST_SOURCE

      - name: Commit changes
        run: |
          git config --global user.name 'Peter Goes'
          git config --global user.email 'petergoes@users.noreply.github.com'
          git add .
          git commit -m "Update syndication link for ${{ github.event.client_payload.source }}"
          git push
